name: Validate JWKS

on:
  push:
    paths:
      - '.well-known/jwks.json'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate JWKS JSON
        run: jq empty .well-known/jwks.json
